# Generated by Django 4.0.2 on 2022-05-28 13:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название', max_length=255, verbose_name='Название')),
                ('price', models.CharField(help_text='Цена', max_length=255, verbose_name='Цена')),
                ('description', models.TextField(help_text='Описание', verbose_name='Описание')),
                ('reviews', models.TextField(blank=True, null=True, verbose_name='Обзор')),
                ('address', models.CharField(help_text='Место положения', max_length=255, verbose_name='Место положения')),
                ('category', models.CharField(choices=[('familly', 'Для семьи'), ('friends', 'С друзьями')], default=('familly', 'Для семьи'), max_length=50)),
                ('averagerating', models.FloatField(default=0)),
                ('soft_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(help_text='Владелец', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Products',
                'verbose_name_plural': 'Product',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=1000)),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_api.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviews',
                'verbose_name_plural': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('path', models.ImageField(max_length=255, upload_to='uploads/products/%Y/%m/%d/')),
                ('soft_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(help_text='Продукт', null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_api.product', verbose_name='Продукты')),
            ],
            options={
                'verbose_name': 'Images',
                'verbose_name_plural': 'Image',
                'ordering': ['-created_at'],
            },
        ),
    ]
