# Generated by Django 4.0.2 on 2022-05-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0002_rename_averagerating_product_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('relax', 'Для отдыха'), ('family', 'Для семьи'), ('friends', 'С друзьями')], default=('relax', 'Для отдыха'), max_length=50),
        ),
    ]
