# Generated by Django 4.0.2 on 2022-06-06 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-created_at'], 'verbose_name': 'Изображении', 'verbose_name_plural': 'Изображение'},
        ),
    ]
