# Generated by Django 4.0.2 on 2022-06-22 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_api', '0005_alter_product_options_alter_review_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='author',
            new_name='owner',
        ),
    ]
